/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package in.neebal.avro.weatherdata;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class WeatherData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WeatherData\",\"namespace\":\"in.neebal.avro.weatherdata\",\"fields\":[{\"name\":\"stationNo\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"year\",\"type\":\"int\",\"default\":0},{\"name\":\"temperature\",\"type\":\"int\",\"default\":-1},{\"name\":\"hours\",\"type\":\"int\",\"default\":-1}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence stationNo;
  @Deprecated public int year;
  @Deprecated public int temperature;
  @Deprecated public int hours;

  /**
   * Default constructor.
   */
  public WeatherData() {}

  /**
   * All-args constructor.
   */
  public WeatherData(java.lang.CharSequence stationNo, java.lang.Integer year, java.lang.Integer temperature, java.lang.Integer hours) {
    this.stationNo = stationNo;
    this.year = year;
    this.temperature = temperature;
    this.hours = hours;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return stationNo;
    case 1: return year;
    case 2: return temperature;
    case 3: return hours;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: stationNo = (java.lang.CharSequence)value$; break;
    case 1: year = (java.lang.Integer)value$; break;
    case 2: temperature = (java.lang.Integer)value$; break;
    case 3: hours = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'stationNo' field.
   */
  public java.lang.CharSequence getStationNo() {
    return stationNo;
  }

  /**
   * Sets the value of the 'stationNo' field.
   * @param value the value to set.
   */
  public void setStationNo(java.lang.CharSequence value) {
    this.stationNo = value;
  }

  /**
   * Gets the value of the 'year' field.
   */
  public java.lang.Integer getYear() {
    return year;
  }

  /**
   * Sets the value of the 'year' field.
   * @param value the value to set.
   */
  public void setYear(java.lang.Integer value) {
    this.year = value;
  }

  /**
   * Gets the value of the 'temperature' field.
   */
  public java.lang.Integer getTemperature() {
    return temperature;
  }

  /**
   * Sets the value of the 'temperature' field.
   * @param value the value to set.
   */
  public void setTemperature(java.lang.Integer value) {
    this.temperature = value;
  }

  /**
   * Gets the value of the 'hours' field.
   */
  public java.lang.Integer getHours() {
    return hours;
  }

  /**
   * Sets the value of the 'hours' field.
   * @param value the value to set.
   */
  public void setHours(java.lang.Integer value) {
    this.hours = value;
  }

  /** Creates a new WeatherData RecordBuilder */
  public static in.neebal.avro.weatherdata.WeatherData.Builder newBuilder() {
    return new in.neebal.avro.weatherdata.WeatherData.Builder();
  }
  
  /** Creates a new WeatherData RecordBuilder by copying an existing Builder */
  public static in.neebal.avro.weatherdata.WeatherData.Builder newBuilder(in.neebal.avro.weatherdata.WeatherData.Builder other) {
    return new in.neebal.avro.weatherdata.WeatherData.Builder(other);
  }
  
  /** Creates a new WeatherData RecordBuilder by copying an existing WeatherData instance */
  public static in.neebal.avro.weatherdata.WeatherData.Builder newBuilder(in.neebal.avro.weatherdata.WeatherData other) {
    return new in.neebal.avro.weatherdata.WeatherData.Builder(other);
  }
  
  /**
   * RecordBuilder for WeatherData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WeatherData>
    implements org.apache.avro.data.RecordBuilder<WeatherData> {

    private java.lang.CharSequence stationNo;
    private int year;
    private int temperature;
    private int hours;

    /** Creates a new Builder */
    private Builder() {
      super(in.neebal.avro.weatherdata.WeatherData.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(in.neebal.avro.weatherdata.WeatherData.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing WeatherData instance */
    private Builder(in.neebal.avro.weatherdata.WeatherData other) {
            super(in.neebal.avro.weatherdata.WeatherData.SCHEMA$);
      if (isValidValue(fields()[0], other.stationNo)) {
        this.stationNo = data().deepCopy(fields()[0].schema(), other.stationNo);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.year)) {
        this.year = data().deepCopy(fields()[1].schema(), other.year);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.temperature)) {
        this.temperature = data().deepCopy(fields()[2].schema(), other.temperature);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.hours)) {
        this.hours = data().deepCopy(fields()[3].schema(), other.hours);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'stationNo' field */
    public java.lang.CharSequence getStationNo() {
      return stationNo;
    }
    
    /** Sets the value of the 'stationNo' field */
    public in.neebal.avro.weatherdata.WeatherData.Builder setStationNo(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.stationNo = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'stationNo' field has been set */
    public boolean hasStationNo() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'stationNo' field */
    public in.neebal.avro.weatherdata.WeatherData.Builder clearStationNo() {
      stationNo = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'year' field */
    public java.lang.Integer getYear() {
      return year;
    }
    
    /** Sets the value of the 'year' field */
    public in.neebal.avro.weatherdata.WeatherData.Builder setYear(int value) {
      validate(fields()[1], value);
      this.year = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'year' field has been set */
    public boolean hasYear() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'year' field */
    public in.neebal.avro.weatherdata.WeatherData.Builder clearYear() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'temperature' field */
    public java.lang.Integer getTemperature() {
      return temperature;
    }
    
    /** Sets the value of the 'temperature' field */
    public in.neebal.avro.weatherdata.WeatherData.Builder setTemperature(int value) {
      validate(fields()[2], value);
      this.temperature = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'temperature' field has been set */
    public boolean hasTemperature() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'temperature' field */
    public in.neebal.avro.weatherdata.WeatherData.Builder clearTemperature() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'hours' field */
    public java.lang.Integer getHours() {
      return hours;
    }
    
    /** Sets the value of the 'hours' field */
    public in.neebal.avro.weatherdata.WeatherData.Builder setHours(int value) {
      validate(fields()[3], value);
      this.hours = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'hours' field has been set */
    public boolean hasHours() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'hours' field */
    public in.neebal.avro.weatherdata.WeatherData.Builder clearHours() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public WeatherData build() {
      try {
        WeatherData record = new WeatherData();
        record.stationNo = fieldSetFlags()[0] ? this.stationNo : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.year = fieldSetFlags()[1] ? this.year : (java.lang.Integer) defaultValue(fields()[1]);
        record.temperature = fieldSetFlags()[2] ? this.temperature : (java.lang.Integer) defaultValue(fields()[2]);
        record.hours = fieldSetFlags()[3] ? this.hours : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
